### ISSUE TITLE
Allow to specify pool size

### ISSUE THREAD

**Issue by astec** [themester/GoSlaves#1]
Why not to allow user to specify pool size in `NewPool()`? If `0` passed can default to the current implementation.

Also would be good if you add a benchmark comparison with https://github.com/gammazero/workerpool I have a suspicion the last one should be faster though I'm not 100% sure and I like the simplicity of  your implementation. But you should address possible bug - https://github.com/themester/GoSlaves/issues/2

**Comment by themester** [comment]
https://github.com/themester/GoSlaves/commit/30ff0446f81b5c9c8d078cd8c86978200cf71f76
